# Generated by Django 6.0.1 on 2026-01-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_shape',
            field=models.CharField(blank=True, default='Oval', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lustre_bias',
            field=models.CharField(blank=True, default='Natural High Shine', max_length=50),
        ),
    ]
